version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo Running tests...
      - mvn clean test
artifacts:
  files:
    - target/reports/**/*
  discard-paths: yes  
